%\documentclass[final,hyperref={hidelinks,pdfpagelabels=false}]{beamer}
\documentclass{beamer}
\usepackage{ebgaramond}
\newcommand{\fakebf}{\fontfamily{mdugm}\fontseries{b}\selectfont}
%% reset default
\renewcommand{\rmdefault}{cmss}
\usepackage{grffile}
\mode<presentation>{\usetheme{mcmaster}}

\usepackage{wrapfig}
% \usepackage{picins} %% ??? screws up tikz ????
\usepackage[english]{babel}
\usepackage[latin1]{inputenc}
\usepackage{amsmath,amsthm, amssymb, latexsym}
\usefonttheme[onlymath]{serif}

%% You can change the poster orientation (portrait vs. landscape) and the paper size (a0, a1, &c.) here:
\usepackage[orientation=portrait,size=a0,scale=1.4,debug]{beamerposter}

\usepackage{array,booktabs,tabularx}
\newcolumntype{Z}{>{\centering\arraybackslash}X} % centered tabularx columns
\newcommand{\pphantom}{\textcolor{ta3aluminium}} % phantom introduces a vertical space in p formatted table columns??!!

% http://tex.stackexchange.com/questions/13423/how-to-change-the-color-of-href-links-for-real
\hypersetup{hidelinks}

%% MY MACROS %%
\newcommand{\R}{{\mathcal R}}
\newcommand{\Ro}{\mathcal{R}_0}
\newcommand{\Ihat}{{\hat{I}}}
\newcommand{\Imin}{I_{\rm min}}
\newcommand{\etal}{\emph{et al.}}
\newcommand{\fref}[1]{Figure~\ref{fig:#1}}

<<pkgs,warning=FALSE,message=FALSE, echo = FALSE>>=
library("knitr")
library("ggplot2"); theme_set(theme_bw(base_size = 32,
                                       base_family = "Times"))
opts_chunk$set(echo=FALSE,error=FALSE)
if (.Platform$OS.type=="windows") {
    windowsFonts(Times=windowsFont("Times"))
} 
zero_margin <- theme(panel.margin=grid::unit(0,"lines"))
zero_x_margin <-
    theme(panel.margin.x=grid::unit(0, "lines"))
library("MASS")
## use Dark2 rather than Set1 because colour #6 of Set1 is yellow (ugh/too light)
scale_colour_discrete <- function(...,palette="Dark2") scale_colour_brewer(...,palette=palette)
scale_fill_discrete <- function(...,palette="Dark2") scale_fill_brewer(...,palette=palette)
library("gridExtra")
library("plyr")  ## for ldply()
library("dplyr") ## for full_join()
library("reshape2")  ## for melt()
library("GGally") ## need BMB version
## devtools::install_github("bbolker/GGally")
## devtools::install_github("lionel-/ggstance")
library("ggstance")
@

<<load, echo = FALSE>>=
load("../simdata/combine_ev_LHS4.rda")
@

<<setup2,echo=FALSE>>=
orig_sum_labs <- c("peak_time","peak_vir","eq_vir","rel_peak")
new_sum_labs <- c("peak time","peak virulence","equilibrium virulence","relative peak")
fixfac2 <- function(x,atop=FALSE,newlines=FALSE) {
    if (atop) new_sum_labs <-
                  gsub("(.*) (.*)","atop(\\1,\\2)",new_sum_labs)
    factor(x,
           levels=orig_sum_labs,
           labels=new_sum_labs)
}
@

<<setup3,echo=FALSE,cache=TRUE>>=
source("../R/hivFuns.R")
source("../R/Param.R")
ltab_mean <- apply(HIVpars_range, 1, geom_mean)
HIVpars.base <- as.HIVvirparlist(ltab_mean)
Lspvl <- "$\\log_{10}~\\textrm{SPVL}$"
pars <- expand(HIVpars.base)
dd <-with(pars,
     melt(data.frame(alpha=alpha,"transmission probability"=Beta2,
                     "duration (years)"=Duration2,check.names=FALSE),
          id.vars="alpha"))
gg_tradeoff <- ggplot(dd,aes(alpha,value))+facet_wrap(~variable,scale="free")+
    geom_line(size=10)+
    labs(x= Lspvl,y="")
@

%%%\title{\huge On the Persistence of Invading Pathogens}
\title{\fakebf{HIV virulence evolution in structured epidemic models}}

\author{\fakebf\href{http://www.math.mcmaster.ca/bolker/}{Ben Bolker and Sang Woo Park}}
\email{\href{mailto:bolker@mcmaster.ca}{\texttt{bolker@mcmaster.ca}}}
%% URL for project (footer)
\projurl{\texttt{https://github.com/bbolker/HIV\_LHS/}}
\institute[McMaster University]{McMaster University, Hamilton, Ontario, Canada 
%%\\\vspace{5mm}\texttt{earn@math.mcmaster.ca}
}
%\institute[]{}
\date[June 2016]{June 2016}

%% Uncomment the following line to define a custom logo (or to tweak the size of the logo)
\McMasterLogo{\includegraphics[width=\WhenPortrait{1.75}{1}\linewidth]{images/Maclogo}}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\newlength{\columnheight}
\setlength{\columnheight}{105cm}

\newlength{\topcolumnheight}
\setlength{\topcolumnheight}{50cm}

\newlength{\bottomcolumnheight}
\setlength{\bottomcolumnheight}{30cm}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\begin{document}
\begin{frame}
%\includegraphics[width=\textwidth]{images/photobanner.pdf}
  \vspace{0.5cm}
  \noindent
\begin{columns}
    % ---------------------------------------------------------%
  \begin{column}{.33\textwidth}
    \begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}
      \begin{minipage}[T]{.95\textwidth}
        \parbox[t][\columnheight]{\textwidth}{ 

\vspace{-2.4 cm} % shouldn't need this??
\begin{block}{Summary}
\noindent
\hspace{-1.6cm}
Pathogens can evolve rapidly in response to changing
conditions (e.g., epidemic stage or public health interventions). 
Models of \textbf{eco-evolutionary dynamics} often
neglect important epidemiological processes, such as the 
dynamics of sexual partnerships. We
compared \textbf{models with a range of complexity} 
of partnership dynamics and extra-partnership contact.
\end{block}

\vspace{0.5cm}

\begin{block}{Tradeoff theory}

\includegraphics[width=0.95\textwidth]{figure/tradeoff.pdf}

\begin{itemize}
\item virulence evolution mediated by transmission-vs-clearance tradeoff
\item still debated \cite{EbertBull2003,alizon_adaptive_2015}
\item HIV \cite{fraser_virulence_2014}: \textbf{set-point viral load} ($\approx$ ``virulence'')
      correlated with transmission probability, rate of progression to AIDS (data from Rakai, Uganda)
\item eco-evolutionary virulence dynamics: \cite{shirreff_transmission_2011}
\end{itemize}

\end{block}

\vspace{0.5cm}

\begin{block}{Epidemiological structure}

  %\vspace{-3cm}
  \begin{center}
    \includegraphics[width=\textwidth]{images/champ1.png} \\
    Champredon \etal\ 2013 \cite{champredon_hiv_2013}
  \end{center}

\textbf{infection} from (1) infected partner ($SI$ couples);
(2) other coupled inf.; (3) uncoupled inf.

\vspace{0.4cm}

Simplified disease model (single stage only)

\vspace{0.4cm}

\begin{itemize}
\item \textbf{pair formation}: instantaneous or delayed?
\item \textbf{extra-pair contact} (epc): present or absent?
\item \textbf{implicit model}: no explicit partnerships,
  force of infection expression derived from $\Ro$ of pair-formation
  model (without epc)
\item \textbf{random-mixing model}: standard SIR model
\end{itemize}

\end{block}

\begin{block}{Parameter uncertainty/exploration}
% https://www.sharelatex.com/learn/Wrapping_text_around_figures
  \setlength{\abovecaptionskip}{0pt}
  \setlength{\belowcaptionskip}{0pt}
  \setlength{\intextsep}{0pt}
  \setlength{\textfloatsep}{0pt}
% \begin{wrapfigure}{l}{0.6\textwidth}
%%\begin{columns}
%%  \begin{column{0.5
%%\begin{center}
  
%\pichskip{15pt}% Horizontal gap between picture and text
%\parpic[l][t]{%
%  \begin{minipage}{0.6\textwidth}
    \includegraphics[width=0.25\textwidth]{images/LHScrop.png}
%  \end{minipage}
%}
%%  \end{center}
%\caption{}
%\end{wrapfigure}
\begin{itemize}
  \item Latin hypercube sampling: parameters from
    \cite{champredon_hiv_2013}
  \item parameters calibrated across models to the same \textbf{initial epidemic growth rate} ($r$)
\end{itemize}
\end{block}
}
\end{minipage}
\end{beamercolorbox}
\end{column}

\begin{column}{.65\textwidth}

\begin{columns}
  \begin{column}{.5\textwidth}
    \begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}
      \begin{minipage}[T]{.95\textwidth}
        \parbox[t][\topcolumnheight]{\textwidth}{ 

\begin{block}{Eco-evolutionary dynamics}

\includegraphics[width=0.95\textwidth]{figure/virtraj.pdf}

\vspace{0.5cm}

\begin{itemize}
\item \textbf{80\% of total variability} in peak SPVL is among- vs. within-model
\item least (random) and most (pairform+epc) models \textbf{most similar}:
  single individuals and extra-pair contact wash out effects of structure
\item implicit model is \textbf{most different}
\item random-mixing model underestimates variability
\end{itemize}

\end{block}       
     
        } % end parbox
        \end{minipage}
    \end{beamercolorbox}
  \end{column}

  \begin{column}{.5\textwidth}
    \begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}
      \begin{minipage}[T]{.95\textwidth} % tweaks the width, makes a new \textwidth
        \parbox[t][\topcolumnheight]{\textwidth}{ 
            
            \begin{block}{Univariate summaries}
              \includegraphics[width=0.7\textwidth]{figure/univ_scheme.pdf}

              \vspace{1cm}
              \includegraphics[width=0.95\textwidth]{figure/univ.pdf}
\begin{itemize}
\item peak timing: epc $>$ finite pair-formation effects
\item equilibrium virulence: interaction
\item low-equilibrium outcomes for intermediate-complexity models
\end{itemize}

            \end{block}
            \vspace{0.5cm}

        } % end parbox
        \end{minipage}
      \end{beamercolorbox}
    \end{column}

\end{columns}

\begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}
  \begin{minipage}[T]{.95\textwidth} % tweaks the width, makes a new \textwidth
    \parbox[t][30cm]{\textwidth}{ % must be some better way to set

\begin{block}{Sensitivity}
<<sens,dev="png",echo=FALSE,fig.width=20,fig.height=10,cache=TRUE,out.width="0.95\\textwidth">>=
mL3 <- subset(mL2,
       !((model=="implicit" &
          LHSvar %in% c("rho_base","c_u_ratio","c_e_ratio")) |
         (model=="random" &
          LHSvar %in% c("rho_base","c_u_ratio","c_e_ratio")) |
         (model=="instswitch" &
          LHSvar %in% c("rho_base","c_u_ratio","c_e_ratio")) |
         (model=="instswitch+epc" &
          LHSvar %in% c("rho_base","c_u_ratio")) |
         (model=="pairform" &
          LHSvar %in% c("c_u_ratio","c_e_ratio"))))
## reorder factors
mL3$LHSvar <- factor(mL3$LHSvar,
                     levels=c("Beta1","Beta3",
                              "Duration1","Duration3",
                              "c_mean_base","c_e_ratio","rho_base",
                              "c_u_ratio"),
                     labels = c("beta[P]", "beta[D]", "D[P]", "D[D]",
                                "c", "c[e]/c[w]", "rho", "c[u]/c[w]"))

## FIXME: could also use labels argument to rename levels, labeller=label_parsed
## in facet_grid to get pretty math

mL3$model <- factor(mL3$model, c("random","pairform+epc", "pairform", "instswitch+epc","instswitch" , "implicit"))

mL3$sumvar <- fixfac2(mL3$sumvar)

L <- function(labels,multi_line=TRUE) {
    r <- if (all(grepl(" ",labels[[1]]))) {
             list(as.character(gsub(" ","\n",labels[[1]])))
    } else {
        label_parsed(labels,multi_line=multi_line)
    }
    return(r)
}

brkfun <- function(x) {
    nx <- 1
    n <- 2
    brks <- axisTicks(log(x), log=TRUE,  nint = n)
    ## browser()
    brks <- brks[brks>x[1] & brks<x[2]]
    nx <- length(brks)
    ## cat("brk1",brks,"\n")
    while (nx<2 && n<10) {
        n <- n+1
        ## cat(n,"\n")
        brks <- axisTicks(log10(x), log=TRUE,  nint = n)
        brks <- brks[brks>x[1] & brks<x[2]]
        ## cat("brk2",brks,"\n")
        nx <- length(brks)
    }
    if (n==10) browser()
    r <- brks[c(1,length(brks))]
    ## hacks
    if (all(r==c(0.01,1))) r <- c(0.02,0.5)
    if (all(r==c(0.2,5))) r <- c(0.5,5)
    return(r)
}
    
ggplot(mL3,aes(LHSval,sumval,colour=model))+
    geom_point(pch=".",alpha=0.5)+
    facet_grid(sumvar~LHSvar,scales="free",
               labeller = L)+
    geom_smooth(se=FALSE)+labs(x="",y="")+
    ## leave a little extra room?
    scale_x_log10(expand=c(0,0.08),breaks=brkfun)+
    zero_margin
@
\end{block}
}
        \end{minipage}
    \end{beamercolorbox}

\begin{columns}
    \begin{column}{.5\textwidth}
      \begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}
        \begin{minipage}[T]{.95\textwidth} % tweaks the width, makes a new \textwidth
          \parbox[t][\bottomcolumnheight]{\textwidth}{ 

\begin{block}{Conclusions and open questions}

\begin{itemize}
\item Random-mixing models best matched the most realistic models; extra-pair and uncoupled individuals washed out the effects
of epidemiological structure
\item Implicit models did worst
\item Variation among models (model structure) $\approx$ variation within models (parameter uncertainty)
\item Large differences
in evolutionary dynamics among different epidemiological models
$\to$ caution in predicting evolutionary responses
\item \textbf{neglected:} disease life history details, sex workers, age-structured mixing \dots
agent-based models?
\end{itemize}

\end{block}
}
        \end{minipage}
      \end{beamercolorbox}
    \end{column}
    \begin{column}{.5\textwidth}
      \begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}
        \begin{minipage}[T]{.95\textwidth} % tweaks the width, makes a new \textwidth
          \parbox[t][\bottomcolumnheight]{\textwidth}{ 

\begin{block}{References}

{\tiny
%% Add numbered references
\setbeamertemplate{bibliography item}[text]
%% Stop line breaks
\setbeamertemplate{bibliography entry title}{}
\setbeamertemplate{bibliography entry location}{}
\setbeamertemplate{bibliography entry note}{}
%% Stop font color changes
% \setbeamercolor*{bibliography item}{fg=black}
% \setbeamercolor*{bibliography entry title}{fg=black}
% \setbeamercolor*{bibliography entry author}{fg=black}
% \setbeamercolor*{bibliography entry location}{fg=black}
% \setbeamercolor*{bibliography entry note}{fg=black} 
%% Generate bibliography
\bibliographystyle{vancouver}
\bibliography{../ms/virulence}
}
\end{block}

\begin{block}{Acknowledgements}

We thank C. Fraser and D. Champredon for code access and 
the Natural Sciences and Engineering Research Council of Canada (NSERC)
for funding.

\end{block}

}
        \end{minipage}
      \end{beamercolorbox}
    \end{column}
    \end{columns}
 \end{column}  % end right-hand 2/3 column
 \end{columns}  % end 50/50 columns
\end{frame}
\end{document}


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%% Local Variables: 
%%% mode: latex
%%% TeX-PDF-mode: t
%%% End:
