---
title: "Figures"
output: html_document
---

```{r pkgs,warning=FALSE,message=FALSE, echo = FALSE}
library("knitr")
library("ggplot2"); theme_set(theme_bw(base_size = 12,
                                       base_family = "Times"))
library("dplyr")
library("tidyr")
opts_chunk$set(echo=FALSE,error=FALSE)
if (.Platform$OS.type=="windows") {
    windowsFonts(Times=windowsFont("Times"))
} 
zero_margin <- theme(panel.margin=grid::unit(0,"lines"))
zero_x_margin <-
    theme(panel.margin.x=grid::unit(0, "lines"))
library("MASS")
## use Dark2 rather than Set1 because colour #6 of Set1 is yellow (ugh/too light)
scale_colour_discrete <- function(...,palette="Dark2") scale_colour_brewer(...,palette=palette)
scale_fill_discrete <- function(...,palette="Dark2") scale_fill_brewer(...,palette=palette)
library("gridExtra")
library("plyr")  ## for ldply()
library("dplyr") ## for full_join()
library("reshape2")  ## for melt()
library("GGally") ## need BMB version
## devtools::install_github("bbolker/GGally")
## devtools::install_github("lionel-/ggstance")
library("ggstance")
```

```{r load, echo = FALSE}
load("../simdata/combine_ev_LHS4.rda")
```

```{r setup2,echo=FALSE}
orig_sum_labs <- c("peak_time","peak_vir","eq_vir","rel_peak")
new_sum_labs <- c("peak time","peak virulence","equilibrium virulence","relative peak")
fixfac2 <- function(x,atop=FALSE,newlines=FALSE) {
    if (atop) new_sum_labs <-
                  gsub("(.*) (.*)","atop(\\1,\\2)",new_sum_labs)
    factor(x,
           levels=orig_sum_labs,
           labels=new_sum_labs)
}

```


### Figure 1

```{r fig1,fig.height=3.5,fig.width=10, echo = FALSE, dpi = 600}
for (i in c("","2","3")) 
    load(sprintf("../simdata/ev_LHS_resS%s.rda",i))
Ls <- load("../simdata/shirreff_data.rda")
tvec <- seq(from=1,by = 0.1,length.out=nrow(vir_matS))
dimnames(vir_matS) <- list(Time=tvec,
                           run=paste0("r=",c(0.021,0.042,0.084)))

d_littleR_m <- melt(vir_matS,value.name="Mean.VL")
shirreff_df_m <- subset(res_sum_df,run==1,select=c(run,Time, Mean.VL))
shirreff_df_m$run <- "Shirreff"
df_tot <- rbind(shirreff_df_m,d_littleR_m)
tlab <- "time (years)"
g1 <- ggplot(df_tot,aes(x=Time,y=Mean.VL,colour=run))+
    geom_line()+labs(x=tlab,y=expression(mean~virulence~(log[10]~SPVL)))+
    theme(legend.position=c(0.75,0.25))
###
dimnames(vir_matS2) <- list(Time=tvec,
               run=c("10^{-3}", "10^{-4}", "10^{-5}"))
g2 <- g1 %+% melt(vir_matS2,id.var="Time",value.name="Mean.VL") +
	labs(y = "")
###
dimnames(vir_matS3) <- list(Time=tvec,
                            run=c("2.5", "3", "3.5"))

vir_matM3 <- melt(vir_matS3,id.var="Time",value.name="Mean.VL")
vir_matM3$run = factor(vir_matM3$run, levels = c("2.5", "3", "3.5"))

g3 <- g1 %+% vir_matM3 +
	labs(y = "")
limits <- c(2.5,4.7)
breaks <- seq(limits[1],limits[2], by = 0.5)
afun <- function(label,size=8) {
    annotate(geom="text",label=label,x=10,y=Inf,
             ## http://stackoverflow.com/questions/20083700/how-to-have-annotated-text-style-to-inherit-from-theme-set-options
             family= theme_get()$text[["family"]],
             size=size,
             vjust=1.5,hjust=0.1)
             ## vjust=0.98,hjust=0.02)
}
g1.y <- g1 + scale_y_continuous(limits = limits, breaks = breaks)+
    scale_colour_discrete(name="run")+afun("a")

g2.labs <- list(bquote(10^{-3}), bquote(10^{-4}), bquote(10^{-5}))

g2.y <- g2 + scale_y_continuous(limits = limits, breaks = breaks)+
    scale_colour_discrete(name="I(0)", labels = g2.labs)+afun("b")
g3.y <- g3 + scale_y_continuous(limits = limits, breaks = breaks)+
        scale_colour_discrete(name=bquote(alpha(0)))+afun("c")
grid.arrange(g1.y, g2.y, g3.y, nrow=1)
```

### Figure 2

```{r fig2, fig.width=6, fig.height = 4, echo = FALSE, cache = TRUE,dpi = 400}

ss <- subset(sum_list[["vir_mat"]],tvec<750)

ss$model <- factor(ss$model, c("random","pairform+epc", "pairform","instswitch+epc","instswitch","implicit"))

gg_virtraj <- ggplot(ss,
                     aes(tvec,mean,ymin=lwr,ymax=upr))+
	geom_line(aes(colour=model,linetype=model),lwd=1)+
	geom_ribbon(aes(fill = model), alpha=0.3)+
	labs(x="time (years)",y=expression(mean~virulence~(log[10]~SPVL))) +
	theme(axis.title.y = element_text(margin = margin(0,10,0,0)),
		axis.title.x = element_text(margin = margin(10,0,0,0))) +
	facet_wrap(~model, nrow = 2) +
	zero_margin
	
## scale_x_continuous(limits=c(0,2500))
print(gg_virtraj)

```

### Figure 2.1 - Transmission rate

```{r fig2.1, fig.width=6, fig.height = 4, echo = FALSE, cache = TRUE,dpi = 400} 

source("../R/hivFuns.R")
source("../R/Param.R")

returnBeta <- function(lSpvl, parameters){
	with(as.list(c(parameters)),{
		v = 10^lSpvl
		return(hill(K,Bmax,v,a))
	})
}

ss2 <- transform(ss, mean = returnBeta(mean,HIVpars.skeleton),
								 lwr = returnBeta(lwr,HIVpars.skeleton),
								 upr = returnBeta(upr,HIVpars.skeleton))


gg_betatraj <- ggplot(ss2,
                     aes(tvec,mean,ymin=lwr,ymax=upr))+
	geom_line(aes(colour=model,linetype=model),lwd=1)+
	geom_ribbon(aes(fill = model), alpha=0.3)+
	labs(x="time (years)",y=expression(mean~transmission~rate~during~asymptomatic~stage)) +
	theme(axis.title.y = element_text(margin = margin(0,10,0,0)),
		axis.title.x = element_text(margin = margin(10,0,0,0))) +
	facet_wrap(~model, nrow = 2) +
	zero_margin
	
## scale_x_continuous(limits=c(0,2500))
print(gg_betatraj)

```

### Figure 2.2 - Duration

```{r fig2.2, fig.width=6, fig.height = 4, echo = FALSE, cache = TRUE,dpi = 400} 
returnDur <- function(lSpvl, parameters){
	with(as.list(c(parameters)),{
		v = 10^lSpvl
		return(hill(v,Dmax,D50,h))
	})
}

ss3 <- transform(ss, mean = returnDur(mean,HIVpars.skeleton),
								 lwr = returnDur(lwr,HIVpars.skeleton),
								 upr = returnDur(upr,HIVpars.skeleton))

gg_durtraj <- ggplot(ss3,
                     aes(tvec,mean,ymin=lwr,ymax=upr))+
	geom_line(aes(colour=model,linetype=model),lwd=1)+
	geom_ribbon(aes(fill = model), alpha=0.3)+
	labs(x="time (years)",y=expression(mean~duration~of~asymptomatic~stage)) +
	theme(axis.title.y = element_text(margin = margin(0,10,0,0)),
		axis.title.x = element_text(margin = margin(10,0,0,0))) +
	facet_wrap(~model, nrow = 2) +
	zero_margin
	
## scale_x_continuous(limits=c(0,2500))
print(gg_durtraj)


```

### Figure 3

```{r fig3, fig.width=8,fig.height=4.8, echo = FALSE, cache = TRUE,dpi = 600}

sL <- transform(sum_list[["sum_mat"]],rel_peak=peak_vir/eq_vir)
sL$model <- factor(sL$model, c("random","pairform+epc", "pairform", "instswitch+epc","instswitch" , "implicit"))
mL <- melt(sL,id.vars=c("model","run"))
## horrible hack (but doesn't help); subsample
## w <- which(mL$model=="random")
## mLw <- mL[-sample(w,size=length(w)*9/10,replace=FALSE),]
w <- with(mL,which(model=="random" & variable=="eq_vir"))
rval <- mean(mL$value[w])
mLw <- droplevels(mL[-w,])
mLw$variable <- fixfac2(mLw$variable)

gg_univ <- ggplot(mLw,aes(value,model,fill=model))+
	geom_violinh(width=1)+
	facet_wrap(~variable,scale="free_x")+
	guides(fill=guide_legend(reverse=TRUE))+
	labs(y="")+
	geom_point(data=data.frame(model="random",variable="equilibrium virulence",
                               value=rval),pch=22,size=3,show.legend=FALSE) +
	zero_x_margin
print(gg_univ)

```


### Figure 3.1

```{r fig3.1, fig.width=8,fig.height=4.8, echo = FALSE, cache = TRUE,dpi = 600}

sL$model <- factor(sL$model, c("random","pairform+epc", "pairform", "instswitch+epc","instswitch" , "implicit"))

sL.epi <- transform(sL, eq_t = returnBeta(eq_vir,HIVpars.skeleton),
										peak_t = returnBeta(peak_vir,HIVpars.skeleton),
										eq_dur = returnDur(eq_vir,HIVpars.skeleton),
										peak_dur = returnDur(peak_vir,HIVpars.skeleton))

sL.epi <- sL.epi[,-c(3:6)]

mL.epi <- melt(sL.epi,id.vars=c("model","run"))
## horrible hack (but doesn't help); subsample
## w <- which(mL$model=="random")
## mLw <- mL[-sample(w,size=length(w)*9/10,replace=FALSE),]
w.epi.t <- with(mL.epi,which(model=="random" & variable=="eq_t"))
w.epi.d <- with(mL.epi,which(model=="random" & variable=="eq_dur"))
rval.epi.t <- mean(mL.epi$value[w.epi.t])
rval.epi.d <- mean(mL.epi$value[w.epi.d])
mLw.epi <- droplevels(mL.epi[-c(w.epi.t,w.epi.d),])
mLw.epi$variable <- factor(mLw.epi$variable, levels = c("eq_t", "peak_t", "eq_dur", "peak_dur"),
													 labels = c("Equilbrium asymptomatic transmission rate",
													 					 "Maximum transmission rate",
													 					 "Equilibrium duration of asymptomatic stage",
													 					 "Minimum duration of asymptomatic stage"))

gg_univ.epi <- ggplot(mLw.epi,aes(value,model,fill=model))+
	geom_violinh(width=1)+
	facet_wrap(~variable,scale="free_x")+
	guides(fill=guide_legend(reverse=TRUE))+
	labs(y="")+
	geom_point(data=data.frame(model="random",variable=c("Equilbrium asymptomatic transmission rate",
																											 "Equilibrium duration of asymptomatic stage"),
                               value=c(rval.epi.t, rval.epi.d)),pch=22,size=3,show.legend=FALSE) +
	zero_x_margin
print(gg_univ.epi)

```

```{r sumtab,as.is=TRUE}
rq <- function(x,q,digits=3) {
    round(quantile(x,q),digits)
}
mLtab <- mL.epi %>% group_by(model,variable) %>%
    summarise(lwr=rq(value,0.025),
              med=rq(value,0.5),
              upr=rq(value,0.975)) %>%
    mutate(variable=abbreviate(variable,30)) %>%
    ungroup() %>%
    arrange(variable,model)
kable(mLtab)
```
```{r sumvals,echo=FALSE}
ff <- function(model,variable,r=3) {
    mm <- mLtab[mLtab$model==model & mLtab$variable==variable,3:5]
    round(unlist(mm),r)
}
mindur_random <- ff("random","peak_dur",1)
mindur_pfepc <-  ff("pairform+epc","peak_dur",1)
mindur_implicit  <- ff("implicit","peak_dur",1)
maxt_random <- ff("random","peak_t",2)
maxt_pfepc <- ff("pairform+epc","peak_t",2)
maxt_implicit  <- ff("implicit","peak_t",2)
save(list=ls(pattern="^(maxt|mindur)"),file="../ms/maxminstats.RData")
```
```{r fig4_func, echo = FALSE}
trim_gg <- function(gg,hack_spaces=TRUE) {
    n <- gg$nrow
    gg$nrow <- gg$ncol <- n-1
    v <- 1:n^2
    gg$plots <- gg$plots[v>n & v%%n!=0]
    gg$xAxisLabels <- gg$xAxisLabels[-n]
    gg$yAxisLabels <- gg$yAxisLabels[-1]
    ## ggpairs tries to parse labels, so this fails if they
    ## have spaces in them ... maybe there's a better way?
    if (hack_spaces) {
        gg$xAxisLabels <- gsub("_"," ",gg$xAxisLabels)
        gg$yAxisLabels <- gsub("_"," ",gg$yAxisLabels)
    }
    return(gg)
}

tweak_legends_gg <- function(gg,pos=1.5) {
    n <- gg$nrow
    for (i in 1:n) {
        for (j in 1:n) {
            inner <- getPlot(gg,i,j)
            if (i==1 & j==1) {
                inner <- inner + ggplot2::theme(legend.position=c(pos,0.5)) +
                    guides(colour = guide_legend(override.aes = list(size=6)))
            } else {
                inner <- inner + ggplot2::theme(legend.position="none")
            }
            gg <- putPlot(gg,inner,i,j)
        }
    }
    return(gg)
}
tweak_colours_gg <- function(gg) {
    n <- gg$nrow
    for (i in 1:n) {
        for (j in 1:n) {
            inner <- getPlot(gg,i,j)
            inner <- inner+scale_colour_brewer(palette = 'Dark2')
            gg <- putPlot(gg,inner,i,j)
        }
    }
    return(gg)
}

```

### Figure 4

```{r fig4,fig.width=7,fig.height=7, echo = FALSE, cache = TRUE,dpi = 600}
sL2 <- sL
names(sL2)[na.omit(match(orig_sum_labs,names(sL)))] <- gsub(" ","_",new_sum_labs)
    ## paste0("`",new_sum_labs,"`")
ggp1 <- ggpairs(sL2,
        mapping = ggplot2::aes(color = model),
        columns=3:6,
        legends=TRUE,
        lower = list(continuous = wrap("points",size=0.1)), ## alpha = 0.3,size=0.5)),
        diag = list(continuous = "blankDiag"),
        upper = list(continuous = "blank"))
## http://stackoverflow.com/questions/14711550/is-there-a-way-to-change-the-color-palette-for-ggallyggpairs-using-ggplot
## have to change plot one panel at a time
ggp2 <- tweak_colours_gg(tweak_legends_gg(trim_gg(ggp1)))
## add 1-to-1 line
inner <- getPlot(ggp2,2,1)
inner <- inner+geom_abline(intercept=0,slope=1,lty=2)
ggp2 <- putPlot(ggp2,inner,2,1)
## tweak scale
inner <- getPlot(ggp2,3,1)
inner <- inner+scale_x_continuous(breaks=seq(2.5,4.5,by=0.5))
ggp2 <- putPlot(ggp2,inner,3,1)
print(ggp2,spacingProportion=0)
```

### Figure 5

```{r fig5, echo = FALSE, fig.width = 10, cache = TRUE,dpi = 600}
mL3 <- subset(mL2,
       !((model=="implicit" &
          LHSvar %in% c("rho_base","c_u_ratio","c_e_ratio")) |
         (model=="random" &
          LHSvar %in% c("rho_base","c_u_ratio","c_e_ratio")) |
         (model=="instswitch" &
          LHSvar %in% c("rho_base","c_u_ratio","c_e_ratio")) |
         (model=="instswitch+epc" &
          LHSvar %in% c("rho_base","c_u_ratio")) |
         (model=="pairform" &
          LHSvar %in% c("c_u_ratio","c_e_ratio"))))
## reorder factors
mL3$LHSvar <- factor(mL3$LHSvar,
                     levels=c("Beta1","Beta3",
                              "Duration1","Duration3",
                              "c_mean_base","c_e_ratio","rho_base",
                              "c_u_ratio"),
                     labels = c("beta[P]", "beta[D]", "D[P]", "D[D]",
                                "c", "c[e]/c[w]", "rho", "c[u]/c[w]"))

## FIXME: could also use labels argument to rename levels, labeller=label_parsed
## in facet_grid to get pretty math

mL3$model <- factor(mL3$model, c("random","pairform+epc", "pairform", "instswitch+epc","instswitch" , "implicit"))

mL3$sumvar <- fixfac2(mL3$sumvar)

L <- function(labels,multi_line=TRUE) {
    r <- if (all(grepl(" ",labels[[1]]))) {
             list(as.character(gsub(" ","\n",labels[[1]])))
    } else {
        label_parsed(labels,multi_line=multi_line)
    }
    return(r)
}

brkfun <- function(x) {
    nx <- 1
    n <- 2
    brks <- axisTicks(log(x), log=TRUE,  nint = n)
    ## browser()
    brks <- brks[brks>x[1] & brks<x[2]]
    nx <- length(brks)
    ## cat("brk1",brks,"\n")
    while (nx<2 && n<10) {
        n <- n+1
        ## cat(n,"\n")
        brks <- axisTicks(log10(x), log=TRUE,  nint = n)
        brks <- brks[brks>x[1] & brks<x[2]]
        ## cat("brk2",brks,"\n")
        nx <- length(brks)
    }
    if (n==10) browser()
    r <- brks[c(1,length(brks))]
    ## hacks
    if (all(r==c(0.01,1))) r <- c(0.02,0.5)
    if (all(r==c(0.2,5))) r <- c(0.5,5)
    return(r)
}
    
ggplot(mL3,aes(LHSval,sumval,colour=model))+
    geom_point(pch=".",alpha=0.5)+
    facet_grid(sumvar~LHSvar,scales="free",
               labeller = L)+
    geom_smooth(se=FALSE)+labs(x="",y="")+
    ## leave a little extra room?
    scale_x_log10(expand=c(0,0.08),breaks=brkfun)+
    zero_margin
```
